/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_msgMod(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_msgMod(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_msgMod(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


    #include "msg.h"
    #include <stdint.h>


#include <stdint.h>		// Use the C99 official header


static uint8_t *new_uint8_t_arr(int nelements) { 
  return (uint8_t *) calloc(nelements,sizeof(uint8_t)); 
}

static void delete_uint8_t_arr(uint8_t *ary) { 
  free(ary); 
}

static uint8_t uint8_t_arr_getitem(uint8_t *ary, int index) {
    return ary[index];
}
static void uint8_t_arr_setitem(uint8_t *ary, int index, uint8_t value) {
    ary[index] = value;
}

typedef union {
  union {
    union {
      struct {
        uint16_t chipAddr;
        uint16_t __reserved0;
        uint16_t rdLen;
        uint16_t wrLen;
        uint8_t  wrBuff[4096];
      } req;
      
      struct {
        uint16_t chipAddr;
        uint16_t __reserved0;
        uint16_t rdLen;
        uint16_t __reserved1;
        uint8_t  rdBuff[4096];
      } resp;
    } v1;
  } tran;
} MsgPayload_i2c;

typedef union {
  union {
    struct {
      uint16_t chipAddr;
      uint16_t __reserved0;
      uint16_t rdLen;
      uint16_t wrLen;
      uint8_t  wrBuff[4096];
    } req;
    
    struct {
      uint16_t chipAddr;
      uint16_t __reserved0;
      uint16_t rdLen;
      uint16_t __reserved1;
      uint8_t  rdBuff[4096];
    } resp;
  } v1;
} MsgPayload_i2c_tran;

typedef union {
  struct {
    uint16_t chipAddr;
    uint16_t __reserved0;
    uint16_t rdLen;
    uint16_t wrLen;
    uint8_t  wrBuff[4096];
  } req;
  
  struct {
    uint16_t chipAddr;
    uint16_t __reserved0;
    uint16_t rdLen;
    uint16_t __reserved1;
    uint8_t  rdBuff[4096];
  } resp;
} MsgPayload_i2c_tran_v1;

typedef struct {
  uint16_t chipAddr;
  uint16_t __reserved0;
  uint16_t rdLen;
  uint16_t wrLen;
  uint8_t  wrBuff[4096];
} MsgPayload_i2c_tran_v1_req;

typedef struct {
  uint16_t chipAddr;
  uint16_t __reserved0;
  uint16_t rdLen;
  uint16_t __reserved1;
  uint8_t  rdBuff[4096];
} MsgPayload_i2c_tran_v1_resp;


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_uint8_t_arr(int jarg1) {
  void * jresult ;
  int arg1 ;
  uint8_t *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (uint8_t *)new_uint8_t_arr(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_uint8_t_arr(void * jarg1) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  
  arg1 = (uint8_t *)jarg1; 
  delete_uint8_t_arr(arg1);
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_uint8_t_arr_getitem(void * jarg1, int jarg2) {
  unsigned char jresult ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  uint8_t result;
  
  arg1 = (uint8_t *)jarg1; 
  arg2 = (int)jarg2; 
  result = (uint8_t)uint8_t_arr_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uint8_t_arr_setitem(void * jarg1, int jarg2, unsigned char jarg3) {
  uint8_t *arg1 = (uint8_t *) 0 ;
  int arg2 ;
  uint8_t arg3 ;
  
  arg1 = (uint8_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (uint8_t)jarg3; 
  uint8_t_arr_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgHdr_signature_set(void * jarg1, unsigned short jarg2) {
  struct MsgHdr *arg1 = (struct MsgHdr *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (struct MsgHdr *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->signature = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgHdr_signature_get(void * jarg1) {
  unsigned short jresult ;
  struct MsgHdr *arg1 = (struct MsgHdr *) 0 ;
  uint16_t result;
  
  arg1 = (struct MsgHdr *)jarg1; 
  result = (uint16_t) ((arg1)->signature);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgHdr() {
  void * jresult ;
  struct MsgHdr *result = 0 ;
  
  result = (struct MsgHdr *)calloc(1, sizeof(struct MsgHdr));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgHdr(void * jarg1) {
  struct MsgHdr *arg1 = (struct MsgHdr *) 0 ;
  
  arg1 = (struct MsgHdr *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_get(void * jarg1) {
  void * jresult ;
  union MsgPayload *arg1 = (union MsgPayload *) 0 ;
  MsgPayload_i2c *result = 0 ;
  
  arg1 = (union MsgPayload *)jarg1; 
  result = (MsgPayload_i2c *)& ((arg1)->i2c);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload() {
  void * jresult ;
  union MsgPayload *result = 0 ;
  
  result = (union MsgPayload *)calloc(1, sizeof(union MsgPayload));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload(void * jarg1) {
  union MsgPayload *arg1 = (union MsgPayload *) 0 ;
  
  arg1 = (union MsgPayload *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c *arg1 = (MsgPayload_i2c *) 0 ;
  MsgPayload_i2c_tran *result = 0 ;
  
  arg1 = (MsgPayload_i2c *)jarg1; 
  result = (MsgPayload_i2c_tran *)& ((arg1)->tran);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload_i2c() {
  void * jresult ;
  MsgPayload_i2c *result = 0 ;
  
  result = (MsgPayload_i2c *)calloc(1, sizeof(MsgPayload_i2c));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload_i2c(void * jarg1) {
  MsgPayload_i2c *arg1 = (MsgPayload_i2c *) 0 ;
  
  arg1 = (MsgPayload_i2c *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c_tran *arg1 = (MsgPayload_i2c_tran *) 0 ;
  MsgPayload_i2c_tran_v1 *result = 0 ;
  
  arg1 = (MsgPayload_i2c_tran *)jarg1; 
  result = (MsgPayload_i2c_tran_v1 *)& ((arg1)->v1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload_i2c_tran() {
  void * jresult ;
  MsgPayload_i2c_tran *result = 0 ;
  
  result = (MsgPayload_i2c_tran *)calloc(1, sizeof(MsgPayload_i2c_tran));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload_i2c_tran(void * jarg1) {
  MsgPayload_i2c_tran *arg1 = (MsgPayload_i2c_tran *) 0 ;
  
  arg1 = (MsgPayload_i2c_tran *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c_tran_v1 *arg1 = (MsgPayload_i2c_tran_v1 *) 0 ;
  MsgPayload_i2c_tran_v1_req *result = 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1 *)jarg1; 
  result = (MsgPayload_i2c_tran_v1_req *)& ((arg1)->req);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c_tran_v1 *arg1 = (MsgPayload_i2c_tran_v1 *) 0 ;
  MsgPayload_i2c_tran_v1_resp *result = 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1 *)jarg1; 
  result = (MsgPayload_i2c_tran_v1_resp *)& ((arg1)->resp);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload_i2c_tran_v1() {
  void * jresult ;
  MsgPayload_i2c_tran_v1 *result = 0 ;
  
  result = (MsgPayload_i2c_tran_v1 *)calloc(1, sizeof(MsgPayload_i2c_tran_v1));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload_i2c_tran_v1(void * jarg1) {
  MsgPayload_i2c_tran_v1 *arg1 = (MsgPayload_i2c_tran_v1 *) 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1 *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_chipAddr_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->chipAddr = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_chipAddr_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  result = (uint16_t) ((arg1)->chipAddr);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp___reserved0_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->__reserved0 = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp___reserved0_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  result = (uint16_t) ((arg1)->__reserved0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_rdLen_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->rdLen = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_rdLen_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  result = (uint16_t) ((arg1)->rdLen);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp___reserved1_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->__reserved1 = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp___reserved1_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  result = (uint16_t) ((arg1)->__reserved1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_rdBuff_set(void * jarg1, void * jarg2) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint8_t *arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  {
    size_t ii;
    uint8_t *b = (uint8_t *) arg1->rdBuff;
    for (ii = 0; ii < (size_t)4096; ii++) b[ii] = *((uint8_t *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_resp_rdBuff_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  result = (uint8_t *)(uint8_t *) ((arg1)->rdBuff);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload_i2c_tran_v1_resp() {
  void * jresult ;
  MsgPayload_i2c_tran_v1_resp *result = 0 ;
  
  result = (MsgPayload_i2c_tran_v1_resp *)calloc(1, sizeof(MsgPayload_i2c_tran_v1_resp));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload_i2c_tran_v1_resp(void * jarg1) {
  MsgPayload_i2c_tran_v1_resp *arg1 = (MsgPayload_i2c_tran_v1_resp *) 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_resp *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_chipAddr_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->chipAddr = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_chipAddr_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  result = (uint16_t) ((arg1)->chipAddr);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req___reserved0_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->__reserved0 = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req___reserved0_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  result = (uint16_t) ((arg1)->__reserved0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_rdLen_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->rdLen = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_rdLen_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  result = (uint16_t) ((arg1)->rdLen);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_wrLen_set(void * jarg1, unsigned short jarg2) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  arg2 = (uint16_t)jarg2; 
  if (arg1) (arg1)->wrLen = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_wrLen_get(void * jarg1) {
  unsigned short jresult ;
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint16_t result;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  result = (uint16_t) ((arg1)->wrLen);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_wrBuff_set(void * jarg1, void * jarg2) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint8_t *arg2 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  {
    size_t ii;
    uint8_t *b = (uint8_t *) arg1->wrBuff;
    for (ii = 0; ii < (size_t)4096; ii++) b[ii] = *((uint8_t *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MsgPayload_i2c_tran_v1_req_wrBuff_get(void * jarg1) {
  void * jresult ;
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  result = (uint8_t *)(uint8_t *) ((arg1)->wrBuff);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MsgPayload_i2c_tran_v1_req() {
  void * jresult ;
  MsgPayload_i2c_tran_v1_req *result = 0 ;
  
  result = (MsgPayload_i2c_tran_v1_req *)calloc(1, sizeof(MsgPayload_i2c_tran_v1_req));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MsgPayload_i2c_tran_v1_req(void * jarg1) {
  MsgPayload_i2c_tran_v1_req *arg1 = (MsgPayload_i2c_tran_v1_req *) 0 ;
  
  arg1 = (MsgPayload_i2c_tran_v1_req *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Msg_hdr_set(void * jarg1, void * jarg2) {
  struct Msg *arg1 = (struct Msg *) 0 ;
  struct MsgHdr *arg2 = (struct MsgHdr *) 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  arg2 = (struct MsgHdr *)jarg2; 
  if (arg1) (arg1)->hdr = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Msg_hdr_get(void * jarg1) {
  void * jresult ;
  struct Msg *arg1 = (struct Msg *) 0 ;
  struct MsgHdr *result = 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  result = (struct MsgHdr *)& ((arg1)->hdr);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Msg_payload_set(void * jarg1, void * jarg2) {
  struct Msg *arg1 = (struct Msg *) 0 ;
  union MsgPayload *arg2 = (union MsgPayload *) 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  arg2 = (union MsgPayload *)jarg2; 
  if (arg1) (arg1)->payload = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Msg_payload_get(void * jarg1) {
  void * jresult ;
  struct Msg *arg1 = (struct Msg *) 0 ;
  union MsgPayload *result = 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  result = (union MsgPayload *)& ((arg1)->payload);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Msg() {
  void * jresult ;
  struct Msg *result = 0 ;
  
  result = (struct Msg *)calloc(1, sizeof(struct Msg));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Msg(void * jarg1) {
  struct Msg *arg1 = (struct Msg *) 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_getMsgSize() {
  int jresult ;
  int result;
  
  result = (int)getMsgSize();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_typeCastMsgToUint8(void * jarg1) {
  void * jresult ;
  struct Msg *arg1 = (struct Msg *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (struct Msg *)jarg1; 
  result = (uint8_t *)typeCastMsgToUint8(arg1);
  jresult = (void *)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

