//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Msg : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Msg(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Msg obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Msg() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msgModPINVOKE.delete_Msg(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MsgHdr hdr {
    set {
      msgModPINVOKE.Msg_hdr_set(swigCPtr, MsgHdr.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = msgModPINVOKE.Msg_hdr_get(swigCPtr);
      MsgHdr ret = (cPtr == global::System.IntPtr.Zero) ? null : new MsgHdr(cPtr, false);
      return ret;
    } 
  }

  public MsgPayload payload {
    set {
      msgModPINVOKE.Msg_payload_set(swigCPtr, MsgPayload.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = msgModPINVOKE.Msg_payload_get(swigCPtr);
      MsgPayload ret = (cPtr == global::System.IntPtr.Zero) ? null : new MsgPayload(cPtr, false);
      return ret;
    } 
  }

  public Msg() : this(msgModPINVOKE.new_Msg(), true) {
  }

}
