//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class msgMod {
  public static SWIGTYPE_p_unsigned_char new_uint8_t_arr(int nelements) {
    global::System.IntPtr cPtr = msgModPINVOKE.new_uint8_t_arr(nelements);
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

  public static void delete_uint8_t_arr(SWIGTYPE_p_unsigned_char ary) {
    msgModPINVOKE.delete_uint8_t_arr(SWIGTYPE_p_unsigned_char.getCPtr(ary));
  }

  public static byte uint8_t_arr_getitem(SWIGTYPE_p_unsigned_char ary, int index) {
    byte ret = msgModPINVOKE.uint8_t_arr_getitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index);
    return ret;
  }

  public static void uint8_t_arr_setitem(SWIGTYPE_p_unsigned_char ary, int index, byte value) {
    msgModPINVOKE.uint8_t_arr_setitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index, value);
  }

  public static int getMsgSize() {
    int ret = msgModPINVOKE.getMsgSize();
    return ret;
  }

  public static SWIGTYPE_p_unsigned_char typeCastMsgToUint8(Msg msg) {
    global::System.IntPtr cPtr = msgModPINVOKE.typeCastMsgToUint8(Msg.getCPtr(msg));
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    return ret;
  }

}
