//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MsgPayload_i2c_tran : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MsgPayload_i2c_tran(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MsgPayload_i2c_tran obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MsgPayload_i2c_tran() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msgModPINVOKE.delete_MsgPayload_i2c_tran(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MsgPayload_i2c_tran_v1 v1 {
    get {
      global::System.IntPtr cPtr = msgModPINVOKE.MsgPayload_i2c_tran_v1_get(swigCPtr);
      MsgPayload_i2c_tran_v1 ret = (cPtr == global::System.IntPtr.Zero) ? null : new MsgPayload_i2c_tran_v1(cPtr, false);
      return ret;
    } 
  }

  public MsgPayload_i2c_tran() : this(msgModPINVOKE.new_MsgPayload_i2c_tran(), true) {
  }

}
